### ISSUE TITLE
Hide description when no translation is available

### ISSUE THREAD

**Issue by Treeways** [Prismwork/EMIffect#8]
Some effects are not properly given a description in the lang file:

![image](https://github.com/Prismwork/EMIffect/assets/56928485/d8b20094-557e-44d5-aebe-6de37af34d65)

I'm running 1.20.1 on Quilt 0.20.2, with EMIffect 1.1.1+mc1.20.1

**Comment by Treeway7** [comment]
An error is thrown in the console every time it fails to deserialize the translation:

```
[17:05:40] [Thread-29/ERROR]: [EMI] Exception deserializing stack {"type":"jemi","uid":"effect:bakery:sweets"}
[17:05:40] [Thread-29/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.deserialize(com.google.gson.JsonElement)" because the return value of "java.util.Map.get(Object)" is null
[17:05:40] [Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiIngredientSerializers.deserialize(EmiIngredientSerializers.java:74)
[17:05:40] [Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.getDeserialized(EmiIngredientSerializer.java:23)
[17:05:40] [Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiSidebars.load(EmiSidebars.java:96)
[17:05:40] [Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiPersistentData.load(EmiPersistentData.java:42)
[17:05:40] [Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:201)
[17:05:40] [Thread-29/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Treeways** [comment]
An error is thrown each time the string fails to deserialize, for each effect without a description:

```
[Thread-29/ERROR]: [EMI] Exception deserializing stack {"type":"jemi","uid":"effect:bakery:sweets"}
[Thread-29/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.deserialize(com.google.gson.JsonElement)" because the return value of "java.util.Map.get(Object)" is null
[Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiIngredientSerializers.deserialize(EmiIngredientSerializers.java:74)
[Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.api.stack.serializer.EmiIngredientSerializer.getDeserialized(EmiIngredientSerializer.java:23)
[Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiSidebars.load(EmiSidebars.java:96)
[Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiPersistentData.load(EmiPersistentData.java:42)
[Thread-29/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:201)
[Thread-29/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by moechakucha** [comment]
see #18.
